services:
  db:
    image: postgres:16
    container_name: saecomp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./create-tables.sql:/docker-entrypoint-initdb.d/init.sql
